### ISSUE TITLE
Cannot use 'A' or 'P' to identify AM or PM in times

### ISSUE THREAD

**Issue by dagronf** [erica/now#2]
On macOS 10.15, the dateFormat 'a' expects either AM or PM according to the tr35 date spec

[http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns](http://www.unicode.org/reports/tr35/tr35-31/tr35-dates.html#Date_Format_Patterns)

The example in the documentation `now --at 4:30P sao paolo` returns an 'unable to parse time' error.  Changing `P` to `PM` resolves the error.

```
user:$ ./now --at 4:30P Sao Paolo Brazil 
Error: timeParseFailure
```

**Comment by dagronf** [comment]
Just on a side note, the city `Sao Paolo` returns no results here in Australia.  

```
user:$ ./now --at 4:30PM sao paolo
Error: Error Domain=kCLErrorDomain Code=8 "(null)"
```

I'm not sure that it's something to do with being in Australia (most likely the case)

**Comment by erica** [comment]
```
% now --at 4:30P sao paolo
São Paulo 9:30:00 PM (GMT-3 Brasilia Standard Time)
% now --at 4:30PM sao paolo
São Paulo 9:30:00 PM (GMT-3 Brasilia Standard Time)
```

It works for me, but I can update the docs 

Also, try Sao Paolo Brazil and see if that works

Thanks!

**Comment by dagronf** [comment]
Ah Sao Paolo Brazil works perfectly!

**Comment by erica** [comment]
> Ah Sao Paolo Brazil works perfectly!

How weird is it that! Maybe you're hitting different server wrt to the geocoding

**Comment by dagronf** [comment]
Interestingly -

```
dford:$ ./now --at 4:30P Sao Paolo Brazil 
Error: timeParseFailure
```

**Comment by erica** [comment]
Let me only mention `PM` officially then

**Comment by dagronf** [comment]
I agree with you.  It's going to have to be something to do with the geocoding server.  At the end of the day it's not a huge issue (as I'd probably just have re-tried with a more specific city string).  I was just being lazy (as usual!) and tried copy/pasting from the docs.

Thank you so much for following up on this!

**Comment by erica** [comment]
Please check the commit I just pushed to address:

* P and A vs PM/AM
* sao paolo brazil (vs sao paolo)

Thanks!

**Comment by erica** [comment]
I missed one Sao Paolo, updating the commit... Hold on. 

Should be updated now!

**Comment by dagronf** [comment]
Perfect!

```
user:$ ./now sao paolo brazil
São Paulo 10:59:07 pm (GMT-3 Brasilia Standard Time)
```

```
user:$ ./now --at 4:30PM sao paolo brazil
São Paulo 3:30:00 am (GMT-3 Brasilia Standard Time)
```

```
user:$ ./now --when 4:30PM sao paolo brazil
Local 5:30:00 am (AEST Australian Eastern Time)
```

**Comment by erica** [comment]
Please also check the site README for another pair of eyes as well as the help message

**Comment by erica** [comment]
Also interesting:

```
% now melbourne
Melbourne 12:03:03 PM (GMT+10 Eastern Australia Time)
```

"Eastern Australia Time" vs "Australian Eastern Time", plus the diff on the time zone naming

```
% now lincoln memorial
Lincoln Memorial 10:06:04 PM (EDT Eastern Time)
% now sydney opera house
Sydney Opera House 12:06:11 PM (GMT+10 Eastern Australia Time)
% now uluru 
Error: Error Domain=kCLErrorDomain Code=8 "(null)"
% now uluru australia
Ayers Rock – Uluru 11:36:30 AM (GMT+9:30 Australian Central Standard Time)
```

**Comment by dagronf** [comment]
Yeah it's odd for sure.  But I suppose it's bouncing of a different server, plus our Australian region settings can be weird too. Guess the local geocoding server specs are different

```
user:$ ./now melbourne
Melbourne 12:05:45 pm (AEST Australian Eastern Time)
user:$ ./now sydney opera house
Sydney Opera House 12:07:22 pm (AEST Australian Eastern Time)
user:$ ./now uluru australia
Ayers Rock – Uluru 11:38:21 am (ACST Australian Central Standard Time)
```

And weirdly

```
user:$ ./now uluru
Ayers Rock – Uluru 11:39:41 am (ACST Australian Central Standard Time)
```

And

```
user:$ ./now lincoln memorial
Memorial Gardens 3:13:29 am (GMT+1 United Kingdom Time)
```

**Comment by dagronf** [comment]
The updates to the README and the help message look fine.  Thank you!

**Comment by erica** [comment]
Thank you!!! Closing.
